server:
  port: 8083
spring:
  application:
    name: booking-service
  jpa:
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/booking
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  #  sql:
  #    init:
  #      mode:
  #      schema-locations: classpath:init-schema.sql
  #      platform: postgres