package com.hotel.booking.system.common.common.enums;

public enum RoomType {
    SINGLE_ROOM, STANDARD_DOUBLE_ROOM, STANDARD_TWIN_ROOM, DELUXE_DOUBLE_ROOM, STUDIO_ROOM_OR_APARTMENT,
    JUNIOR_SUITE, EXECUTIVE_SUITE, PRESIDENTIAL_SUITE
}
