server:
  port: 8032
spring:
  application:
    name: hotel-service
  jpa:
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/customer
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
#  sql:
#    init:
#      mode:
#      schema-locations: classpath:init-schema.sql
#      platform: postgres